name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate config
        run: |
          /opt/prometheus/promtool check config ${{ github.workspace }}/prometheus.yml

      - name: Move config
        run: |
          cp ${{ github.workspace }}/prometheus.yml /opt/prometheus/prometheus.yml
      
      - name: Apply config
        run: |
          curl -X POST http://localhost:9090/-/reload
